---
- name: Create VM from a full clone of a template
  community.general.proxmox_kvm:
    node: "{{ proxmox_template_node }}"
    api_host: "{{ proxmox_api_host | default(omit) }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_pass | default(omit) }}"
    api_token_id: "{{ proxmox_api_token | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_port: "{{ proxmox_api_port }}"
    target: "{{ proxmox_target_node }}"
    clone: "{{ template_name }}"
    vmid: "{{ template_id }}"
    name: "{{ new_vm_name }}"
    agent: 'enabled=1'
    autostart: "{{ proxmox_autostart }}"
    storage: "{{ proxmox_storage }}"
    state: "{{ proxmox_vm_state }}"
    timeout: 120
  when: not new_vm_name in proxmox_discovered_vms
  register: clone_vm_job

- name: Debug clone job
  ansible.builtin.debug:
    msg: "Clone job: {{ clone_vm_job }}"
