---
- name: Discover all existing Virtual Machines
  community.general.proxmox_vm_info:
    api_host: "{{ proxmox_api_host | default(omit) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
  register: proxmox_discovered_vms

- name: Debug
  ansible.builtin.debug:
    msg: "Proxmox discovered VMs: {{ proxmox_discovered_vms }}"

- name: Collect Proxmox VM IDs to allow for proper iteration
  ansible.builtin.set_fact:
    proxmox_vm_ids: "{{ proxmox_vm_ids | default({}) | combine({item.name: item.vmid}) }}"
  loop: "{{ proxmox_discovered_vms.proxmox_vms }}"
  when: not item.template and item.type == 'qemu'

- name: Debug 2
  ansible.builtin.debug:
    msg: "Proxmox VM IDs: {{ proxmox_vm_ids }}"

- name: Construct list of template IDs
  ansible.builtin.set_fact:
    template_id: "{{ item.vmid }}"
  loop: "{{ proxmox_discovered_vms.proxmox_vms }}"
  when:
    - item.template
    - item.name == template_name

- name: Debug 3
  ansible.builtin.debug:
    msg: "Proxmox Template ID: {{ template_id }}"
